services:
  cachet:
    image: mundiale/cachet:0.1
    ports:
      - 8000:8000
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=192.168.0.106
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-base64:1G2nnCabkeCuYCUfbqxo8PvUQ8YuiTUpd+gXeBZbwhc=}
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
